pipeline {
  agent any

  parameters {
    string(name: 'build_version', defaultValue: 'v1', description: 'Build version to use for Docker image')
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Satyams-git/devops-demo-project-12.git'
      }
    }

    stage('Build and Test') {
      steps {
        sh 'cd demo-java-app && mvn clean package'
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          def dockerImage = docker.build(
            "devopssakshi/demo-java-app:${params.build_version}",
            "demo-java-app"
          )

          
          }
        }
      }
    }
  }
}
